name: Terraform and Kubernetes Deployment

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "eu-west-1"

jobs:
  terraform_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: cd Dan.Accessment-master/terraform-eks && terraform init

      - name: Format Terraform Code
        run: cd Dan.Accessment-master/terraform-eks && terraform fmt

      - name: Validate Terraform
        run: Dan.Accessment-master/terraform-eks && terraform validate

      - name: Plan Infrastructure Changes
        run: |
          cd Dan.Accessment-master/terraform-eks
          terraform plan
          read -p "Are you sure to proceed?" -n 1 -r
          echo
          if [[ $REPLY =~ ^[Yy]$ ]]; then
            terraform apply --auto-approve
          else
            echo "Aborted."
            exit 1
          fi

      - name: Deploy Nginx Application
        run: |
          aws eks update-kubeconfig --name rova_eks_cluster
          kubectl apply -f terraform-eks/EKS/ConfigurationFiles/deployment.yaml
          kubectl apply -f terraform-eks/EKS/ConfigurationFiles/service.yaml
